# Generated by Django 4.2.1 on 2023-05-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_userstatus_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="last_seen",
            field=models.DateTimeField(),
        ),
    ]
