# Generated by Django 4.2.1 on 2023-05-28 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0006_alter_userstatus_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
